//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliTaxi_Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Companies
    {
        [Key, DefaultValue(1)]
        public int ID { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Admin_ID { get; set; }
    }
}
