//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliTaxi_Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Devices
    {
        [Key, DefaultValue(1)]
        public int ID { get; set; }
        public int Type { get; set; }
        public Nullable<double> Location_Lat { get; set; }
        public Nullable<double> Location_Long { get; set; }
        public string Location_Name { get; set; }
        public Nullable<bool> Location_SupportsMap { get; set; }
        public Nullable<System.DateTime> FirstUse { get; set; }
        public Nullable<System.DateTime> LastUse { get; set; }
        public string IP { get; set; }
        public Nullable<bool> On { get; set; }
        public Nullable<int> User_ID { get; set; }
    }
}
