//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliTaxi_Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Orders
    {
        [Key, DefaultValue(1)]
        public int ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        [DisplayName("Data primirii")]
        public Nullable<System.DateTime> DateReg { get; set; }
        [DisplayName("Data preluãrii")]
        public Nullable<System.DateTime> DateTaken { get; set; }
        [DisplayName("Data finalizãrii")]
        public Nullable<System.DateTime> DateLeft { get; set; }
        public Nullable<double> From_Lat { get; set; }
        public Nullable<double> From_Long { get; set; }
        public string From_Name { get; set; }
        public Nullable<bool> From_SupportsMap { get; set; }
        public Nullable<double> Destination_Lat { get; set; }
        public Nullable<double> Destination_Long { get; set; }
        public string Destination_Name { get; set; }
        public Nullable<bool> Destination_SupportsMap { get; set; }
        [DisplayName("Preluatã")]
        public Nullable<bool> Taken { get; set; }
        public Nullable<int> TaxiTaken_ID { get; set; }
        public Nullable<int> Review_ID { get; set; }
    }
}
