//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliTaxi_Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Reviews
    {
        [Key, DefaultValue(1)]
        public int ID { get; set; }
        public Nullable<int> From_ID { get; set; }
        public Nullable<int> For_ID { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        [Range(1,5)]
        [DisplayName("Stele")]
        public Nullable<int> Stars { get; set; }
        [DisplayName("Comentarii")]
        public string Content { get; set; }
    }
}
