//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliTaxi_Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Users
    {
        [Key, DefaultValue(1)]
        public int ID { get; set; }
        public string UserID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Device_ID { get; set; }
    }
}
